# Generated by Django 5.2.8 on 2026-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('done', 'Done'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='not_started', max_length=20),
        ),
    ]
